version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

hooks:
  AfterInstall:
    - location: deploy/scripts/restart-server.sh
      timeout: 300
      runas: root
